library(rOmniDriver)
w <- init_srs()
n <- number_srs(w)
n
get_name(w)
get_firmware_model(w)
get_firmware_version(w)
get_serial_number(w)
bench <- get_bench(w,0)
bench$getGrating()
bench$getFilterWavelength()
bench$getSlitSize()
get_number_of_pixels(w)
get_number_of_dark_pixels(w)
get_number_of_channels(w)
get_maximum_integration_time(w)
get_minimum_integration_time(w)
get_maximum_intensity(w)
get_wavelengths(w)
is_feature_supported_pixel_binning(w,0)
#detector <- get_detector(w,0)
#detector
set_correct_for_electrical_dark(w,1,0)
get_correct_for_electrical_dark(w,0)
set_correct_for_electrical_dark(w,0,0)
get_correct_for_electrical_dark(w,0)
set_correct_for_detector_nonlinearity(w,1,0)
get_correct_for_detector_nonlineary(w,0)
set_correct_for_detector_nonlinearity(w,0,0)
get_correct_for_detector_nonlineary(w,0)
set_boxcar_width(w,2,0)
get_boxcar_width(w,0)
set_boxcar_width(w,0,0)
get_boxcar_width(w,0)

is_feature_supported_internal_trigger(w)
trg <- get_feature_controller_internal_trigger(w)
get_trigger_period_valid_range(trg)
set_trigger_source(trg, 3)
get_trigger_source(trg, char.out = TRUE)
set_trigger_period(trg, 0.1)
get_trigger_period(trg)

spc <- get_spectrum(w,0)
is_saturated(w,0)
is_spectrum_valid(w,0)
set_scans_to_avg(w,2)
set_integration_time(w,500000)
spc <- get_spectrum(w)
is_saturated(w,0)
is_spectrum_valid(w,0)
spc
max(spc)

srs_close(w)
