library(rOmniDriver)
w <- init_srs()
n <- number_srs(w)
bench <- get_bench(w,0)
bench$getGrating()
bench$getFilterWavelength()
bench$getSlitSize()
is_feature_supported_pixel_binning(w,0)
#detector <- get_detector(w,0)
#detector
set_correct_for_electrical_dark(w,0,0)
get_correct_for_electrical_dark(w,0)
set_correct_for_electrical_dark(w,1,0)
get_correct_for_electrical_dark(w,0)
set_correct_for_detector_nonlinearity(w,0,0)
get_correct_for_detector_nonlineary(w,0)
set_correct_for_detector_nonlinearity(w,1,0)
get_correct_for_detector_nonlineary(w,0)
set_boxcar_width(w,2,0)
get_boxcar_width(w,0)
set_boxcar_width(w,0,0)
get_boxcar_width(w,0)
spc <- get_spectrum(w,0)
is_saturated(w,0)
is_spectrum_valid(w,0)
set_scans_to_avg(w,2)
set_integration_time(w,5000000)
spc <- get_spectrum(w)
is_saturated(w,0)
is_spectrum_valid(w,0)
spc

test_args <- function(w) {
  get_name(w)
}

test_args(w)
srs_close(w)
