library(rOO)
w <- init.srs()
n <- number.srs(w)
bench <- get.bench(w,0)
bench$getGrating()
bench$getFilterWavelength()
bench$getSlitSize()
is.feature.supported.pixel.binning(w,0)
#detector <- get.detector(w,0)
#detector
set.correct.for.electrical.dark(w,0,0)
get.correct.for.electrical.dark(w,0)
set.correct.for.electrical.dark(w,1,0)
get.correct.for.electrical.dark(w,0)
set.correct.for.detector.nonlinearity(w,0,0)
get.correct.for.detector.nonlineary(w,0)
set.correct.for.detector.nonlinearity(w,1,0)
get.correct.for.detector.nonlineary(w,0)
set.boxcar.width(w,2,0)
get.boxcar.width(w,0)
set.boxcar.width(w,0,0)
get.boxcar.width(w,0)
spc <- get.spectrum(w,0)
is.saturated(w,0)
is.spectrum.valid(w,0)
set.scans.to.avg(w,2)
set.integration.time(w,5000000)
spc <- get.spectrum(w)
is.saturated(w,0)
is.spectrum.valid(w,0)
spc
srs.close(w)